services:
  client:
    depends_on:
      - server
    build: ./client
    ports:
      - "3000:3000"
  server:
    depends_on:
      - agent
    build: ./server
    ports:
      - "9000:9000"
  agent:
    build: ./agent
    environment:
      GOOGLE_GENAI_USE_VERTEXAI: FALSE
      GOOGLE_API_KEY: AIzaSyA9DnpmNixJ-w0y1JkfJr5ltwm2HEqj1pE
    ports:
      - "8000:8000"
